#!/bin/sh

echo "name,chars,words,lines,maxlinelength,interpreter"
find plugins/node.d* -mindepth 1 -maxdepth 1 -type f | while read plugin; do

  # filter
  if ! head -1 $plugin | grep -q '#!'; then
	  continue
  fi

  # fields: name
  printf "%s" $plugin

  # fields: chars,words,lines,maxlinelength
  wc --chars --words --lines --max-line-length $plugin | awk '{printf ",%s,%s,%s,%s", $1, $2, $3, $4 }'

  # fields: interpreter
  printf ",%s" "$(head -1 $plugin | sed -e 's/^#!//' | xargs)"

  printf "\n"
done
